version: "3.7"

services:

    service_1:
        image: mmcgarrigle/service_1
        ports:
            - "5000:5000"
        networks:
            - mmcgarrigle_network
        depends_on:
            - service_4
        deploy:
            replicas: 4

    service_2:
        image: mmcgarrigle/service_2
        networks:
            - mmcgarrigle_network
        deploy:
            replicas: 4
        
    service_3:
        image: mmcgarrigle/service_3
        networks:
            - mmcgarrigle_network
        deploy:
            replicas: 4
        
    service_4:
        image: mmcgarrigle/service_4
        networks:
            - mmcgarrigle_network
        depends_on:
            - service_2
            - service_3
        deploy:
            replicas: 4
        
networks:
    mmcgarrigle_network:
        driver: overlay